; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = esp32dev

[common]
lib_deps_builtin =
    SPI
    Wire
    SD

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    ${common.lib_deps_builtin}
    stm32duino/STM32duino VL53L4CD@^1.0.5         # ToF sensor long range
    stm32duino/STM32duino VL6180X@^2.0.0          # ToF sensor short range
    adafruit/Adafruit LED Backpack Library@^1.5.1 # LED Matrix
monitor_speed = 115200
upload_speed = 921600
extra_scripts = pre:extra_script.py
